# Generated by Django 5.2.8 on 2025-11-20 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_productcategory_producttype_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='PharmacyAddress',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('region', models.CharField(max_length=60)),
                ('city', models.CharField(max_length=60)),
                ('street', models.CharField(max_length=30)),
                ('apartment', models.CharField(max_length=15)),
                ('postal_code', models.CharField(max_length=8)),
            ],
            options={
                'db_table': 'pharmacy_addresses',
            },
        ),
        migrations.CreateModel(
            name='PharmacyWorkingSchedule',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
            options={
                'db_table': 'pharmacy_working_schedules',
            },
        ),
        migrations.CreateModel(
            name='Pharmacy',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.pharmacyaddress')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.pharmacyworkingschedule')),
            ],
            options={
                'db_table': 'pharmacies',
            },
        ),
    ]
