# Generated by Django 5.2.8 on 2025-11-20 07:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_pharmacyaddress_pharmacyworkingschedule_pharmacy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.pharmacy')),
                ('products', models.ManyToManyField(to='api.product')),
            ],
            options={
                'db_table': 'orders',
            },
        ),
    ]
