# Generated by Django 5.2.8 on 2025-11-21 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_order_id_alter_pharmacy_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pharmacy',
            old_name='schedule',
            new_name='working_schedule',
        ),
    ]
