# Generated by Django 5.2.8 on 2025-11-22 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_order_status_delivery_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='status',
            field=models.CharField(choices=[('Processing', 'Processing'), ('Handover to delivery', 'Handover'), ('In transit', 'In Transit'), ('Ready for pickup', 'Ready'), ('Received', 'Received')], default='Processing'),
        ),
    ]
