# Generated by Django 5.2.8 on 2025-11-22 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_pharmacyworkingschedule_pharmacies'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=60)),
                ('city', models.CharField(max_length=60)),
                ('street', models.CharField(max_length=30)),
                ('apartment', models.CharField(max_length=15)),
                ('postal_code', models.CharField(max_length=8)),
            ],
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='address',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='address', to='api.address'),
        ),
        migrations.DeleteModel(
            name='PharmacyAddress',
        ),
    ]
