# Generated by Django 5.2.8 on 2025-11-24 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_address_pharmacy_address_delete_pharmacyaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='order',
            name='time',
            field=models.TimeField(auto_now=True),
        ),
    ]
