# Generated by Django 5.2.8 on 2025-11-20 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pomfrey_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'product_categoires',
            },
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'product_types',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=30)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('amount', models.IntegerField()),
                ('categories', models.ManyToManyField(to='pomfrey_app.productcategory')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pomfrey_app.producttype')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
