# Generated by Django 5.2.8 on 2025-11-21 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pomfrey_app', '0006_rename_schedule_pharmacy_working_schedule'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='amount',
            new_name='stock',
        ),
    ]
