# Generated by Django 5.2.8 on 2025-11-21 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pomfrey_app', '0007_rename_amount_product_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttype',
            name='categories',
            field=models.ManyToManyField(to='pomfrey_app.productcategory'),
        ),
    ]
