# Generated by Django 5.2.8 on 2025-11-22 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pomfrey_app', '0008_producttype_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Received', 'Received'), ('Cancelled', 'Cancelled')], default='Pending'),
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Pickup', 'Pickup'), ('Delivery', 'Delivery')])),
                ('status', models.CharField(choices=[('Processing', 'Processing'), ('Handover to delivery', 'Handover'), ('In transit', 'In Transit'), ('Ready for pickup', 'Ready'), ('Received', 'Received')])),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pomfrey_app.order')),
            ],
            options={
                'db_table': 'deliveries',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Card', 'Card'), ('Cash', 'Cash')])),
                ('is_paid', models.BooleanField(default=False)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pomfrey_app.order')),
            ],
        ),
    ]
