# Generated by Django 5.2.8 on 2025-11-22 11:22

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pomfrey_app', '0011_alter_delivery_order_alter_payment_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pharmacy',
            name='address',
        ),
        migrations.RemoveField(
            model_name='pharmacy',
            name='working_schedule',
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region='US'),
        ),
        migrations.AddField(
            model_name='pharmacyaddress',
            name='pharmacy',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pharmacy', to='pomfrey_app.pharmacy'),
        ),
        migrations.AddField(
            model_name='pharmacyworkingschedule',
            name='pharmacies',
            field=models.ManyToManyField(null=True, related_name='pharmacies', to='pomfrey_app.pharmacy'),
        ),
    ]
