# Generated by Django 5.2.8 on 2025-11-22 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pomfrey_app', '0012_remove_pharmacy_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmacyworkingschedule',
            name='pharmacies',
            field=models.ManyToManyField(related_name='pharmacies', to='pomfrey_app.pharmacy'),
        ),
    ]
